version: '3.8'

volumes:
  mongo_data:


services:
  db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: books
    volumes:
      - mongo_data:/var/lib/mongo/data
    ports:
      - '27017:27017'
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  app:
    build: .
    environment:
      DATABASE_URL: "mongodb://mongo_admin:password@db:27017"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
